import Modules.Product
from typing import Optional

def search(tag : str, pages: int) -> list[Modules.Product]: ...
def parse(url : str, short_url : bool) -> Optional[Modules.Product]: ...
def parse_sizes(sizes: str) -> list[dict]: ...
def parse_size(size_data: str) -> dict: ...
def product_by_sku(sku: str) -> Optional[Modules.Product]: ...