from logging import Logger
import Modules.Product
from typing import Optional

def search(tag : str, logger: Logger, pages: int) -> list[Modules.Product]: ...
def parse_product(url : str, logger: Logger, short_url : bool) -> Optional[Modules.Product]: ...
def product_by_sku(sku: str, logger: Logger) -> Optional[Modules.Product]: ...