def parse_sizes(sizes: str) -> list[dict]: ...
def parse_size(size_data: str) -> dict: ...
def get_proper_sku(sku: str) -> str: ...
def check_name(tag: str, pattern: str) -> bool: ...
def generate_name_from_pattern(pattern: str) -> str: ...
def get_sku_from_url(url: str) -> str: ...